### ISSUE TITLE
Publish module to forge

### ISSUE THREAD

**Issue by stbenjam** [theforeman/puppet-foreman_scap_client#14]
It was requested to put this up on the forge, any reasons not to?

It needs a spec and probably should get added to foreman's modulesync for integration with blacksmith, et al.

**Comment by shlomizadok** [comment]
this? https://forge.puppetlabs.com/isimluk/foreman_scap_client

**Comment by stbenjam** [comment]
Ah just the messenger, someone was looking for it and didn't see it... I'd think it should go to theforeman org, but i guess you can close this if it'll stay there
