### ISSUE TITLE
Set ensure from present (optional) to latest

### ISSUE THREAD

**Issue by rodehoed** [theforeman/puppet-foreman_scap_client#23]
Hi,

Currently there is an ensure => present for the rubygem-foreman_scap_client in the init.pp. Can this be changed to latest (or at least a class parameter)? We currenly have 0.1.1 installed everywhere but as it contains a put instead of post bug we would like to have the latest version.

**Comment by rodehoed** [comment]
Sorry I have to re-ask my question. This functionality is available on the github (master) version but it's not in the puppet forge module (0.3.8).

**Comment by ares** [comment]
It seems we should bump the puppet module version and update it in the installer, @isimluk could you please do it? Or I can try myself with your help esp. access granting :-)

@rodehoed we use external [issue tracker](http://projects.theforeman.org/projects/openscap/issues/new), please report further issues there. You can use github account for registration/login.

**Comment by isimluk** [comment]
I cannot find a button for granting priviledges on https://forge.puppet.com/isimluk/foreman_scap_client/readme 

I think it makes sense to move the foreman_scap_client puppet forge repo under theforeman umbrella as we did with github and with issue tracker.

**Comment by ares** [comment]
ok, I started working on it

**Comment by ares** [comment]
A 0.3.9 has been released, now under theforeman account - https://forge.puppet.com/theforeman/foreman_scap_client
