### ISSUE TITLE
'remove_foreman_scap_client_cron' path missing /bin, fails on RHEL 6

### ISSUE THREAD

**Issue by xtex404** [theforeman/puppet-foreman_scap_client#28]
Please accept my pull request #27 ... this module now fails on RHEL 6 and CentOS 6 because grep and sed live in /bin, not /usr/bin. I've added /bin to the beginning of the search path in my patch since /bin/grep and /bin/sed exists on RHEL 6 and RHEL 7 servers (although it's a symlink in RHEL 7 to /usr/bin).

**Comment by ares** [comment]
Thanks for the report, I copied the report under our issue tracker, you can find it at [here](http://projects.theforeman.org/issues/16498), therefore I'm closing this one.
