### ISSUE TITLE
Cert path needs to be changed.

### ISSUE THREAD

**Issue by prismhr-smartin** [theforeman/puppet-foreman_scap_client#36]
params.pp currently has the following settings.

class foreman_scap_client::params {
  $downcased_fqdn = downcase($fqdn)
  $ca_file          = pick($::rh_certificate_repo_ca_file, '/var/lib/puppet/ssl/certs/ca.pem')
  $host_certificate = pick($::rh_certificate_consumer_host_cert, "/var/lib/puppet/ssl/certs/${$downcased_fqdn}.pem")
  $host_private_key = pick($::rh_certificate_consumer_host_key, "/var/lib/puppet/ssl/private_keys/${$downcased_fqdn}.pem")
}

Based on puppetlabs PC1 the paths and names of the certs have changed.
The new path is /etc/puppetlabs/puppet/ssl/
And the certs use non fqdn names for pem ie "local-agent01.pem" and not "local-agent01.example.com.pem"

I believe you should adjust the params.pp like the following to adjust for these changes.

class foreman_scap_client::params {
  $downcased_hostname = downcase($hostname)
  $ca_file          = pick($::rh_certificate_repo_ca_file, '/etc/puppetlabs/puppet/ssl/certs/ca.pem')
  $host_certificate = pick($::rh_certificate_consumer_host_cert, "/etc/puppetlabs/puppet/ssl/certs/${$downcased_hostname}.pem")
  $host_private_key = pick($::rh_certificate_consumer_host_key, "/etc/puppetlabs/puppet/ssl/private_keys/${$downcased_hostname}.pem")
}

**Comment by ares** [comment]
Thanks for the report, the change you suggest makes the module incompatible with puppet v3, I wonder if we could somehow find out the certificate file more generic. We could perhaps use 
```
if versioncmp('4.0.0', $clientversion) < 0 {
  $ssl_dir = '/var/lib/puppet/ssl/'
} else {
  $ssl_dir = ''/etc/puppetlabs/puppet/ssl'
}
```

and use $ssl_dir everywhere. I wonder if puppet agent can read the $ssl_dir from puppet.conf in manifest somehow.

**Comment by ares** [comment]
I moved the ticket to our issue tracker, please find it at http://projects.theforeman.org/issues/19471

I also opened a https://github.com/theforeman/puppet-foreman_scap_client/pull/37 with the suggested fix, I would help us if you could test the patch with puppet from PC1 and let us know whether it works for you. I'll close this issue, we can continue discussion at PR itself.

**Comment by prismhr-smartin** [comment]
The following may be simpler.

class foreman_scap_client::params {
  $downcased_fqdn = downcase($fqdn)
  $ca_file          = pick($::rh_certificate_repo_ca_file, "${puppet_ssldir}/certs/ca.pem")
  $host_certificate = pick($::rh_certificate_consumer_host_cert, "${puppet_ssldir}/certs/${$downcased_fqdn}.pem")
  $host_private_key = pick($::rh_certificate_consumer_host_key, "${puppet_ssldir}/private_keys/${$downcased_fqdn}.pem")
}

I have tested this and it does work with PC1.

Note the fqdn\hostname seems to depend on how the server was setup so I left the fqdn.

**Comment by ares** [comment]
`puppet_ssldir` is ssl dir on master I think, we need agent's ssl dir.
