### ISSUE TITLE
Cannot get setup to work.

### ISSUE THREAD

**Issue by prismhr-smartin** [theforeman/puppet-foreman_scap_client#38]
Even after correcting the paths for the foreman_scap_client certs to the PC1 location I cannot get the system to work and I get a cert error. Below are the exact steps needed to re-create the issue on centos7. I have tested this with Formean1.13\Katello3.2 and Foreman1.14\Katelo3.3 and both have the issue. Any help to get this working would be greatly appreciated.

echo $(hostname -I | cut -d" " -f 1) $(hostname -f) $(hostname -s) >> /etc/hosts

yum -y localinstall http://fedorapeople.org/groups/katello/releases/yum/3.3/katello/el7/x86_64/katello-repos-latest.rpm
yum -y localinstall http://yum.theforeman.org/releases/1.14/el7/x86_64/foreman-release.rpm
yum -y localinstall https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
yum -y localinstall http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum -y install foreman-release-scl
yum -y update
yum -y install katello
wget http://copr.fedoraproject.org/coprs/openscapmaint/openscap-latest/repo/epel-7/openscapmaint-openscap-latest-epel-7.repo -O /etc/yum.repos.d/openscapmaint-openscap-latest-epel-7.repo
yum -y install openscap-utils
yum -y install scap-workbench
yum -y install scap-security-guide
sed -i.bak 's/defaults,noexec,nosuid,nodev/defaults,exec,nosuid,nodev/g' /etc/fstab
mount -o remount,exec /tmp
foreman-installer --scenario katello --enable-foreman-proxy --enable-foreman-plugin-openscap --enable-foreman-proxy-plugin-openscap
The command above provides output to the webinterface like the following that you will need.
[root@871225-1gdrs01 yum.repos.d]# foreman-installer --scenario katello --enable-foreman-proxy --enable-foreman-plugin-openscap --enable-foreman-proxy-plugin-openscap
Installing             Done                                               [100%] [......................................................................................]
  Success!
  * Katello is running at https://871225-1gdrs01.davison.local
      Initial credentials are admin / ohaqk3BqKXQQnNBr
  * To install an additional Foreman proxy on separate machine continue by running:

      foreman-proxy-certs-generate --foreman-proxy-fqdn "$FOREMAN_PROXY" --certs-tar "~/$FOREMAN_PROXY-certs.tar"

  The full log is at /var/log/foreman-installer/katello.log
  
Continue running the following commands, note you may need to logout\source your path to get the location of the new puppet binary.

puppet module install theforeman-foreman_scap_client
foreman-rake foreman_openscap:bulk_upload:default
puppet agent -t

Load the web interface https://871225-1gdrs01.davison.local and login admin / ohaqk3BqKXQQnNBr. This information was provided in the command output above.
Click on "Configure" and select "Classes"
Click on "Import environments from 871225-1gdrs01.davison.local"
Select the checkbox for the line returned and click on "Update"
Click on "foreman_scap_client"
Click on the "Smart Class Parameter" tab
Click on "server" and enter "871225-1gdrs01.davison.local" into the "Default value" field
Click on "port" and enter "9090" into the "Default value" field
Click "Submit"

Click on "Hosts" and select "Policies"
Click on "New Policy" and enter the following
Name: test
Description: test
Click "Next"
SCAP Content: Red Hat centos7 default content
XCCDF Profile: Standard System Security
Tailoring File: Choose Tailoring File
Click "Next"
Period: Weekly
Weekday: Thursday
Click "Next"
Click on "Default Location" to move it to "Selected items"
Click "Next"
Click on "Default Organization" to move it to "Selected items"
Click "Next"
Click "Submit"

Click on "Default Organization" scroll to "Default Organization" and select "Any Organization"
Click on "Hosts" and select "All hosts"
Select the checkbox for the only host
Click on "Select Action" and select "Assign Compliance Policy"
Select "test" and click "Submit"

Click "Edit" for the host in the list under "Actions"
Click on the "Puppet Classes" tab
Click "foreman_scap_client" and "foreman_scap_client" to add the class
Click "Submit"

On the host as root run the following
puppet agent -t

This will output the following
[root@871225-1gdrs01 ~]# puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for 871225-1gdrs01.davison.local
Info: Applying configuration version '1493914482'
Notice: /Stage[main]/Foreman_scap_client/Package[rubygem-foreman_scap_client]/ensure: created
Notice: /Stage[main]/Foreman_scap_client/File[foreman_scap_client]/ensure: defined content as '{md5}a8803f874c5876835677f1834671f027'
Notice: /Stage[main]/Foreman_scap_client/File[foreman_scap_client_cron]/ensure: defined content as '{md5}8d78164858509d0e4de71ce9b0258435'
Notice: Applied catalog in 20.27 seconds
[root@871225-1gdrs01 ~]#

It creates the following cron job
[root@871225-1gdrs01 ~]# cat /etc/cron.d/foreman_scap_client_cron
# DO NOT EDIT THIS FILE MANUALLY
# IT IS MANAGED BY PUPPET

# foreman_scap_client cron job

# Runs foreman_scap_client 1
0 1 * * 4 root /usr/bin/foreman_scap_client 1 > /dev/null

If you run the job command manually you get the following error.
[root@871225-1gdrs01 ~]# /usr/bin/foreman_scap_client 1
File /var/lib/openscap/content/9a2614ff536765f4651ff5dd650a393c4c1a4340c8637a8e9bff38cca48fef31.xml is missing. Downloading it from proxy.
Download SCAP content xml from: https://871225-1gdrs01.davison.local:9090/compliance/policies/1/content/9a2614ff536765f4651ff5dd650a393c4c1a4340c8637a8e9bff38cca48fef31
Unable to load certs
No such file or directory - /var/lib/puppet/ssl/certs/871225-1gdrs01.davison.local.pem

This is due to the fact that the repo has not adjusted to the new cert location for puppet. It was in /var/lib/pupppet/ssl but is now in /etc/puppetlabs/puppet/ssl
sed -i 's?/var/lib/puppet/ssl?/etc/puppetlabs/puppet/ssl?g' /etc/foreman_scap_client/config.yaml

Now when you run the cron command manually you get an error about certificates.
[root@871225-1gdrs01 ~]# /usr/bin/foreman_scap_client 1
File /var/lib/openscap/content/9a2614ff536765f4651ff5dd650a393c4c1a4340c8637a8e9bff38cca48fef31.xml is missing. Downloading it from proxy.
Download SCAP content xml from: https://871225-1gdrs01.davison.local:9090/compliance/policies/1/content/9a2614ff536765f4651ff5dd650a393c4c1a4340c8637a8e9bff38cca48fef31
SCAP content is missing and download failed with error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
[root@871225-1gdrs01 ~]#

**Comment by ares** [comment]
If you're using katello, the entitlement certificate should be used for authentication, since the CA in that case is candlepin, not puppet ca. This is why we have `pick` in [there](https://github.com/theforeman/puppet-foreman_scap_client/blob/master/manifests/params.pp#L3). Is that host correctly registered in Katello?

**Comment by prismhr-smartin** [comment]
No I have not started to setup katello yet, I was planning on doing that after I got this working. I was not under the impression that it was required. Is there a way to get it working without setting up the katello agent yet?

If I remove the katello scenario would this work?

Thank you for your assistance!

**Comment by prismhr-smartin** [comment]
When I setup katello agent it does indeed work, yay!!!!
Is there a way to get it working without setting up the katello agent yet?
If I remove the katello scenario would this work?

**Comment by ares** [comment]
I'm afraid it's either "with katello" or "without katello". There's no easy migration from one to the other. If you plan to use katello in future, why not start to do it right away? Just having katello agent installed should do no harm. You could perhaps try to add second CA to the mix by putting the puppet CA certificate somewhere among trusted certificates but I haven't done it myself and it needs experimenting.

**Comment by xprazak2** [comment]
I will close this as the issue seems to be resolved, feel free to reopen if you think this was closed prematurely.
