### ISSUE TITLE
Release on Puppet forge is quite old

### ISSUE THREAD

**Issue by dgoetz** [theforeman/puppet-foreman_scap_client#72]
There was no release to the forge since 0.4.0 which is lacking many features, so bumping the version and pushing a release to the forge would be great! Thanks!

**Comment by ekohl** [comment]
Thanks for the reminder. I've opened https://github.com/theforeman/puppet-foreman_scap_client/pull/73 & https://github.com/theforeman/puppet-foreman_scap_client/pull/74 which will be nice additions.

**Comment by anothermerge** [comment]
Bump.  The current latest release 0.4.0 is quite old and does not have support for Puppet 7 or 8.  Can we get an updated release for this that supports those?

**Comment by ekohl** [comment]
I released 1.0.0.

**Comment by ekohl** [comment]
And I realized I didn't mark it compatible with stdlib 9: https://github.com/theforeman/puppet-foreman_scap_client/pull/77 (and didn't clean up old cruft).
